name: mtp
description: "MomoTalk Plus(MTP) 一款BA学生扮演聊天软件"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  window_manager_plus: ^1.0.5
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  ionicons: ^0.2.2
  go_router: ^14.8.1
  file_picker: ^9.2.1
  share_plus: ^7.1.0
  permission_handler: ^11.4.0
  device_info_plus: ^11.3.3
  elegant_notification: ^2.4.3
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  hive_ce_generator: ^1.8.2
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/student.json
